<a href="https://colab.research.google.com/github/Juhikarn123/Design-analysis-and-algorithm/blob/main/OptimalBinarySearch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math
def optimalBST(p,q,n):
  e=np.zeros((n+1)**2).reshape(n+1,n+1)
  w=np.zeros((n+1)**2).reshape(n+1,n+1)
  root=np.zeros((n+1)**2).reshape(n+1,n+1)
  for i in range(n+1):
    e[i,i]=q[i]
    w[i,i]=q[i]
  for i in range(0,n):
    root[i,i]=i+1
  for l in range(1,n+1):
    for i in range(0,n-l+1):
      j=i+l
      min_=math.inf
      w[i,j]=w[i,j-1]+p[j]+q[j]
      for r in range(i,j):
        t=e[i,r-1+1]+e[r+1,j]+w[i,j]
        if t<min_:
          min_=t
          root[i,j-1]=r+1
  root_pruned=np.delete(np.delete(root,n,1),n,0)
  print("-----e-----")
  print(e)
  print("-----w-----")
  print(w)
  print("-----root-----")
  print(root_pruned)
def main():
  p=[0,0.20,.1,.06,.1,.2]
  q=[.05,.1,.06,.06,.05,.2]
  n=len(p)-1
  optimalBST(p,q,n)
if __name__ =='__main__':
  main()


-----e-----
[[0.05 0.   0.   0.   0.   0.  ]
 [0.   0.1  0.   0.   0.   0.  ]
 [0.   0.   0.06 0.   0.   0.  ]
 [0.   0.   0.   0.06 0.   0.  ]
 [0.   0.   0.   0.   0.05 0.  ]
 [0.   0.   0.   0.   0.   0.2 ]]
-----w-----
[[0.05 0.35 0.51 0.63 0.78 1.18]
 [0.   0.1  0.26 0.38 0.53 0.93]
 [0.   0.   0.06 0.18 0.33 0.73]
 [0.   0.   0.   0.06 0.21 0.61]
 [0.   0.   0.   0.   0.05 0.45]
 [0.   0.   0.   0.   0.   0.2 ]]
-----root-----
[[1. 1. 2. 2. 2.]
 [0. 2. 3. 3. 3.]
 [0. 0. 3. 4. 4.]
 [0. 0. 0. 4. 4.]
 [0. 0. 0. 0. 5.]]
